spring:
  application:
    name: codesentinel-review-service

  datasource:
    url: jdbc:postgresql://localhost:5432/codesentinel_db
    username: tejas
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

openai:
  api-key: ${OPENAI_API_KEY}